name: 'Publish VCD-UI Library'
description: 'Publishes one of the packages in this repo as latest or next'
inputs:
    nx-name:
        description: 'Name of project as used in nx commands'
        required: true

    npm-name:
        description: 'Name of project as will be published to npm'
        required: true

    npm-token:
        description: 'Token to be used when publishing'
        required: true

    npm-publish-tag:
        description: 'what to pass as the --tag option when calling `npm publish`'
        required: true

runs:
    using: "composite"
    steps:
        # Default registry is github's internal npm registry
        - name: Setup Node registry
          uses: actions/setup-node@v3
          with:
              node-version: 16.10.0
              registry-url: https://registry.npmjs.org/
        - uses: bahmutov/npm-install@v1

        - name: 'Publish ${{ inputs.npm-name }}@${{ inputs.npm-publish-tag }}'
          run: |
              npx nx build ${{ inputs.nx-name }} --configuration=production
              cd ./dist/${{ inputs.nx-name }}
              echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
              npm publish --tag ${{ inputs.npm-publish-tag }} --public
          shell: bash
          env:
              NPM_TOKEN: ${{inputs.npm-token}}

