/*!
 * Copyright 2019 VMware, Inc.
 * SPDX-License-Identifier: BSD-2-Clause
 */

/**
 * There are no typing definitions for the compodoc objects so we define them manually here.
 */

import { ApiParameters } from '../documentation-retriever.service';

/**
 * The root object of the compodoc autogenerated documentation (documentation.json)
 */
export interface CompodocSchema {
    components: CompodocComponent[];
}

/**
 * Component description as defined in the Compodoc generated documentation JSON
 */
export interface CompodocComponent {
    name: string;
    description: string;
    sourceCode: string;
    templateData: string;
    styleUrlsData: StyleUrlsData[];
    inputsClass: ApiParameters[];
    outputsClass: ApiParameters[];
}

export interface StyleUrlsData {
    data: string;
}
