name: Publish @vcd/i18n@latest

on: [ workflow_dispatch ]


jobs:
    publish-components:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/publish
              with:
                  nx-name: i18n
                  npm-name: '@vcd/i18n'
                  npm-publish-tag: latest
                  npm-token: ${{ secrets.NPM_TOKEN }}
